version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-leave
    restart: always
    environment:
      POSTGRES_DB: leave_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
    volumes:
      - pgdata-leave:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5438:5432"

  backend:
    build:
      context: ./Backend
    container_name: backend-leave
    restart: always
    ports:
      - "3007:3007"
    depends_on:
      - postgres
    volumes:
      - ./Backend/uploads:/app/uploads

  employee-leave-ui:
    build:
      context: ./employee-leave
    container_name: employee-leave-ui
    ports:
      - "8010:80"

  hr-leave-ui:
    build:
      context: ./hr-leave
    container_name: hr-leave-ui
    ports:
      - "8011:80"

volumes:
  pgdata-leave:

